@url_dev=http://localhost:3055/v1/api/

### signup
POST {{url_dev}}user/signup
Content-Type: application/json 
x_api_key: b96c4a6b44cadf1d6c1be985e8dc71e7addff92046f718dd81c25de47ced1b8b4cb3ad2dc705fe5ae742152288cb0b8339104180ac86312917bcbded7ce4d61d

{
    "fullName": "Nguyễn Thanh Tùng",
    "email": "tungnt2k4yyy00@gmail.com",
    "password" : "30092004",
    "phoneNumber": "0971684280",
    "address": "A51 Ngô Thì Nhậm, La Khê, Hà Đông, Hà Nội"
}