name: Deploy to EC2

on: 
  push:
    branches: 
      - main

jobs: 
  deploy: 
    runs-on: ubuntu-lastest

    steps:
      -name: Deploy via SSH
      user: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          set -e

          cd /var/www/shop
          git pull origin main

          cd backend
          npm install
          pm2 restart shop-backend --update-env

          cd ../frontend
          npm install
          rm -rf dist
          npm run build

          sudo nginx -t
          sudo systemctl reload nginx